### ISSUE TITLE
throttleLatest working in 4.0.8?

### ISSUE THREAD

**Issue by armorik83** [Reactive-Extensions/RxJS#1123]
`source.throttleLatest is not a function` ??
I was sure that `source.throttleLatest()` in 4.0.7 has operated.

**Comment by jamiewinder** [comment]
I've just encountered this too. I'm assuming it got removed as it isn't in the documentation any more. Has this been replaced by something else? Or is there another way to compose a stream to get the same functionality?
